minimon-server: add argument handling

diff --git a/minimon-server b/minimon-server
--- a/minimon-server
+++ b/minimon-server
@@ -12,18 +12,20 @@ set -m
 trap 'clean' EXIT SIGINT SIGTERM
 
 clean(){
-	echo "cleaning"
-	kill -- -$(jobs -p)
-	rm -rf /tmp/mini*
-	exit 0
+	if $STARTED; then
+		echo "cleaning"
+		kill -- -$(jobs -p)
+		rm -rf /tmp/mini*
+		exit 0
+	fi
 }
 
 usage(){
 	echo "MiniMon; made by Misthios
--p : port off the server (defaults to 12345)
+-p : port for the server (defaults to 12345)
 -c : path for the certificate
--v : verify the certificate (defaults to 0 = false
--t : folder which contains the tasks shell scripts (defaults to ./Tasks)
+-v : verify the certificate (defaults to 0 = false)
+-t : folder which contains the tasks shell scripts (defaults to ./Tasks/)
 ";}
 
 setup(){
@@ -38,7 +40,7 @@ setup(){
 
 
 run_server(){
-	 socat -u openssl-listen:12345,fork,reuseaddr,cert=../test.pem,verify=0 PIPE:/tmp/minimon/minimon-in
+	 socat -u openssl-listen:"$PORT",fork,reuseaddr,cert="$CERT",verify="$VERIFY" PIPE:/tmp/minimon/minimon-in
 }
 sort(){
 	while :
@@ -60,6 +62,7 @@ listen(){
 	while :
 	do
 		read msg < /tmp/minimon/hosts/$1
+		echo $msg
 	done
 }
 
@@ -72,13 +75,39 @@ listen_control(){
 	done
 }
 
-#todo: argument handling
+##--------- ARGUMENTS ----------#
+while getopts ':p:t:c:v:h' OPTION; do
+	case "$OPTION" in
+		p) PORT="$OPTARG";;
+		c) CERT="$OPTARG";;
+		t) TASKDIR="$OPTARG";;
+		v) VERIFY="$OPTARG";;
+		h) usage; exit 0;;
+	esac
+done
 
+#default values
+: ${PORT:="12345"}
+: ${TASKDIR:="./Tasks/"}
+: ${VERIFY:=0} #off by default for now
+STARTED=false
+
+
+#Make sure that cert is a valid pem file
+if [ -z "$CERT" ]; then echo "A cert path must be given"; exit 1; fi;
+if ! [ -f "$CERT" ]; then echo "cert not found"; exit 1; fi;
+if ! openssl x509 --noout -in "$CERT"; then echo "cert is not a valid pem"; exit 1; fi;
+
+#Make sure that verify is a number
+re='^[0-9]+$'
+if ! [[ $VERIFY =~ $re ]] ; then echo "Verify must be a number" ; exit 1; fi
+if ! [ "$VERIFY" -ge 0 ] && ["$VERIFY" -le 1 ]; then echo "verify must either be 0 or 1"; exit 1; fi;
 
 setup
 run_server&
 sort&
 listen_control&
+STARTED=true #for the cleanup trap
 
 #todo: replace with shell
 while :
